### ISSUE TITLE
Leaves EMR cluster exposed to the internet

### ISSUE THREAD

**Issue by timothyohare** [awsdocs/aws-data-pipeline-developer-guide#11]
We were following this tutorial and it left an EMR cluster exposed to the internet.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
