### ISSUE TITLE
Documentation completly out of date.

### ISSUE THREAD

**Issue by jovana** [awsdocs/aws-data-pipeline-developer-guide#13]
I have tried to follow these steps to import data: 
https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-import-ddb-save-pipeline-console.html

Source page can found here: doc_source/dp-import-ddb-save-pipeline-console.md

But nothing works anymore. It's frustrating this wrong documentation exists. Because of the lack of documentation the data pipeline is useless.

One error (of many) to give you an idea:
```
eUnable to create resource for @EmrClusterForLoad_2020-11-30T20:57:29 due to: Instance type 'm1.large' is not supported. (Service: AmazonElasticMapReduce; Status Code: 400; Error Code: ValidationException; Request ID: f5995d10-6095-4037-8f77-ad5630541aca; Proxy: null)
```

**Comment by jovana** [comment]
And because of this page is also out of date: https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-emr-supported-instance-types.html It makes this even worse.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
