### ISSUE TITLE
Add exhaustive reference and examples in the documentation

### ISSUE THREAD

**Issue by sergiovm** [awsdocs/aws-data-pipeline-developer-guide#8]
Hello, 

I've been using AWS Data Pipelines for a month and I'd like to share my experience.
I'm sorry to say that I have the feeling the documentation is extremely poor when you are trying to do something more advanced than tweaking the templates provided by AWS during pipeline creation.

Just some examples of problems I've found (but the list is endless):

**I want to send a Failure notification with useful information to help debug or spot the problem without the need to access the logs**
Ok then, I go to the Knowledge Base and I find this: 
https://aws.amazon.com/es/premiumsupport/knowledge-center/sns-notification-error-data-pipeline/
Great, I can send the message with that. Then I see it refers to "Node expressions" to send more information along. Cool! Then let's go to the reference documentation about it:
https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-pipeline-expressions.html
Ok... It gives a couple of examples (#{node.@scheduledStartTime}, #{node.@scheduledEndTime}) and... that's all!! But where's the list of expressions and its meaning? That should be a reference documentation, isn't it?
Since AWS Console doesn't have the full functionality for advanced pipelines and you have to write the definition in a JSON file in your editor and upload it with AWS Cli, you don't have any help like autocompletion or list of properties or whatever. So... I have to guess the possible Node Expressions? Really? How can people work with this?

**I've done a Hive Activity and I want to pass some Bootstrap Actions to it**
Alright, I have my pipeline up & running but I see it's slow as hell. No problem! I've found that I have to pass some parameters along to tell Hive to use more resources (obviously I'm simplifying things here just to illustrate my point about the documentation).
So, what I need is to modify the parameters: 
- mapred.tasktracker.map.tasks.maximum
- mapred.tasktracker.reduce.tasks.maximum

The way you are supposed to do so is by adding a Bootstrap action: 
--bootstrap-action="s3://elasticmapreduce/bootstrap-actions/configure-hadoop -m mapred.tasktracker.map.tasks.maximum=10 -m mapred.tasktracker.reduce.tasks.maximum=10
All reference I can find is about AWS EMR or custom installations of Hadoop/Hive in EC2 instances. Nothing about AWS Data Pipelines. E.g:
- https://docs.aws.amazon.com/emr/latest/ReleaseGuide/EMR_Hive_Optimizing.html
- https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-configure-apps.html

So, how I'm I supposed to pass this parameters along if it is Pipelines the one orchestrating the cluster and I have no access to it? Wait! There's the "bootstrap action" property in the ERM Cluster Resource. This must be the place! Then you face the next problem... it's syntax...
How I'm I supposed to stuff 
--bootstrap-action="s3://elasticmapreduce/bootstrap-actions/configure-hadoop -m mapred.tasktracker.map.tasks.maximum=10 -m mapred.tasktracker.reduce.tasks.maximum=10 
Into that parameter whose help hint is: An action to run when the cluster starts. You can specify comma-separated arguments. To specify multiple actions, up to 255, add multiple bootstrapAction fields. The default behavior is to start the cluster without any bootstrap actions.

Do not panic, it has a "help" link https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-emrcluster.html

Mmmmmm ok it is not really useful but wait! if you are lucky to look at the left navigation menu you find there is an entry for a page with examples! So let's go for it:
https://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/emrcluster-example.html
Ok a list of examples... So, after reviewing them and some try and error (having to delete and recreate the pipeline several times during the process because failed pipelines do not re-activate gracefully and more often than desired they get into an inconsistent state). I manage to translate the bootstrap argument to the expected parameter... but then you get an error saying that the EMR version you are using does not accept that bootstrap action and there's a validation error (whaaaaat??). Dead end...
Then after hours of research I've found the way to pass the parameter properly... guess what? the solution was not in pipelines documentation: 
http://www.rummandba.com/2016/12/dynamodb-restore-using-datapipeline.html
This guy (who I can't thank enough because it saved me literally dozens of research hours) shared a pipeline definition in which he configured another bootstrap parameter but that gave me the lead to finally configure what I wanted.

**Next challenge: activate the pipeline when a file is delivered in a S3 bucket**
Now I want to activate the pipeline when I get certain file in a s3 bucket. I know that I need a lambda triggered by the S3 action that has to activate the Pipeline, but yet again a new documentation desert crossing is waiting for me... All I know is I need to do this: 
aws datapipeline activate-pipeline --pipeline-id {pipelineid} --start-timestamp yyyy-MM-ddThh:mm:ssZ
But from within a lambda function in NodeJS. 
I don't think the use case is so uncommon not to be in the documentation but yet again, I have to learn on my on how to do it.

So... to sum up. I can understand the lack of documentation for a newly created service but AWS Data Pipelines has been around for some years already so, no excuses.
The existing documentation is good but far from enough!

Best,
Sergio.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
